- name: Nginx install & config | Update apt cache
  become: true
  apt: 
    update_cache: yes 
    cache_valid_time: 3600
  ignore_errors: true
  
- name: Nginx install & config | Apt install
  become: True
  ansible.builtin.apt:
    name: 
      - nginx
      - curl
    state: latest
  notify: Nginx start

- name: Nginx install & config | Copy config files
  become: True
  ansible.builtin.template:
    src: templates/site.j2
    dest: /etc/nginx/sites-available/{{ domain_zones }}
    owner: www-data 
    group: www-data 
    mode: 0644

- name: Nginx install & config | Copy config files
  become: True
  ansible.builtin.template:
    src: templates/site.ssl.j2
    dest: /etc/nginx/sites-available/{{ domain_zones }}.ssl
    owner: www-data 
    group: www-data 
    mode: 0644

- name: Nginx install & config | Enable sites
  become: True
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ domain_zones }}
    dest: /etc/nginx/sites-enabled/{{ domain_zones }}
    state: link

- name: Nginx install & config | Enable sites
  become: True
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ domain_zones }}.ssl
    dest: /etc/nginx/sites-enabled/{{ domain_zones }}.ssl
    state: link

- name: Nginx install & config | Delete default config
  become: true
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent