- name: Wordpress | Create www root
  become: true
  ansible.builtin.file:
    path: /var/www/{{ domain_zones }}.{{ my_domain }}
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: Wordpress | Dowload wordpress
  become: true
  ansible.builtin.get_url:
    url: https://wordpress.org/{{ wp_version }}.tar.gz
    dest: /tmp/wordpress-{{ wp_version }}.tar.gz

- name: Wordpress | Extract on /tmp
  become: true
  ansible.builtin.unarchive:
    src: /tmp/wordpress-{{ wp_version }}.tar.gz
    dest: /tmp
    owner: www-data
    group: www-data
    mode: 0755
    copy: no
  
- name: Wordpress | Move in www root
  become: true
  ansible.builtin.command: mv /tmp/wordpress /var/www/{{ domain_zones }}.{{ my_domain }}

- name: Wordpress | Fetch random salts for WordPress config
  ansible.builtin.command: curl https://api.wordpress.org/secret-key/1.1/salt/
  register: wp_salt


- name: Wordpress | Config wordpress
  become: true
  ansible.builtin.template:
    src: templates/wp-config.j2
    dest: /var/www/{{ domain_zones }}.{{ my_domain }}/wordpress/wp-config.php
    mode: 0755
  notify: 
    - Nginx reload